import type { Metadata } from "next";
import ClientThemeProvider from "@/components/theme/themeProvider";
import { Header } from "@/components/pages/layout/header";
import { Footer } from "@/components/pages/layout/footer";
import StyledComponentsRegistry from "@/lib/registry";
import { MainLayout } from "@/components/pages/layout/mainLayout";

export const metadata: Metadata = {
  title: "Maedeh Morajabi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientThemeProvider>
      <html lang="en">
        <body>
          <StyledComponentsRegistry>
            <MainLayout>
              <Header />
              {children}
              <Footer />
            </MainLayout>
          </StyledComponentsRegistry>
        </body>
      </html>
    </ClientThemeProvider>
  );
}
