import type { Metadata } from "next";
import ClientThemeProvider from "@/components/theme/themeProvider";

export const metadata: Metadata = {
  title: "Maedeh Morajabi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientThemeProvider>
      <html lang="en">
        <body>{children}</body>
      </html>
    </ClientThemeProvider>
  );
}
